name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Install sqlcipher
        run: sudo apt-get update && sudo apt-get install -y libsqlcipher-dev

      - name: Run tests
        run: mise run test
